use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        channel, config, env, mcp, notifications, opencode, preferences, recovery, sessions, specs,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        preferences::get_app_version,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        config::get_config_path,
        config::reset_config_file,
        config::load_custom_models,
        config::save_custom_models,
        config::check_legacy_config,
        config::delete_legacy_config,
        config::fetch_models,
        config::get_default_model,
        config::save_default_model,
        config::get_cloud_session_sync,
        config::save_cloud_session_sync,
        config::get_reasoning_effort,
        config::save_reasoning_effort,
        config::get_diff_mode,
        config::save_diff_mode,
        config::get_todo_display_mode,
        config::save_todo_display_mode,
        config::get_include_co_authored_by_droid,
        config::save_include_co_authored_by_droid,
        config::get_show_thinking_in_main_view,
        config::save_show_thinking_in_main_view,
        channel::load_channels,
        channel::save_channels,
        channel::save_channel_credentials,
        channel::get_channel_credentials,
        channel::delete_channel_credentials,
        channel::fetch_channel_tokens,
        channel::fetch_models_by_api_key,
        env::get_env_var,
        env::set_env_var,
        env::remove_env_var,
        env::setup_env_in_shell_config,
        specs::list_specs,
        specs::read_spec,
        specs::rename_spec,
        specs::delete_spec,
        specs::update_spec,
        specs::start_specs_watcher,
        specs::stop_specs_watcher,
        mcp::load_mcp_servers,
        mcp::save_mcp_server,
        mcp::delete_mcp_server,
        mcp::toggle_mcp_server,
        opencode::list_opencode_profiles,
        opencode::get_opencode_profile,
        opencode::save_opencode_profile,
        opencode::delete_opencode_profile,
        opencode::duplicate_opencode_profile,
        opencode::create_default_profile,
        opencode::get_active_opencode_profile_id,
        opencode::apply_opencode_profile,
        opencode::get_opencode_config_status,
        opencode::get_opencode_provider_templates,
        opencode::test_opencode_provider_connection,
        opencode::read_opencode_current_config,
        sessions::list_session_projects,
        sessions::list_sessions,
        sessions::get_session_detail,
        sessions::start_sessions_watcher,
        sessions::stop_sessions_watcher,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
#[cfg(debug_assertions)]
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(all(test, debug_assertions))]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
